### ISSUE TITLE
Gradle Code

### ISSUE THREAD

**Issue by tellfa** [TakeoffAndroid/AppIntroAnimation#3]
hi, please insert Build.Grade code
for example :     compile 'com.android.support:design:22.2.0'

tnx

**Comment by sharish** [comment]
hello,

The project is not kind of library to extend the existing work done. You need to download the source and customize your self as described in the readme.

Thanks,
Harish

**Comment by ckdevrel** [comment]
Thanks @cooltechworks  for your reply. @tellfa Are you clear??. Can i mark this issue as closed?

**Comment by tellfa** [comment]
@TakeoffAndroid , yeah. tnx
